version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: zholamanoff
      POSTGRES_PASSWORD: kb971033
      POSTGRES_DB: crm_db
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: zholamanoff
      POSTGRES_PASSWORD: kb971033
      POSTGRES_DB: crm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
