version: '3'
services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_USER: zholamanoff
      DB_PASSWORD: kb971033
      DB_NAME: crm_db
      DB_HOST: postgres
      DB_PORT: 5432
      JWT_SECRET: b6989f4c50a0b46422a2d123e836c384
    depends_on:
      - postgres

  crm:
    build:
      context: ./services/crm
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      DB_USER: zholamanoff
      DB_PASSWORD: kb971033
      DB_NAME: crm_db
      DB_HOST: postgres
      DB_PORT: 5432
      JWT_SECRET: b6989f4c50a0b46422a2d123e836c384
    depends_on:
      - postgres

  landing:
    build:
      context: ./services/landing
      dockerfile: Dockerfile
    depends_on:
      - auth
      - crm

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - landing

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: zholamanoff
      POSTGRES_PASSWORD: kb971033
      POSTGRES_DB: crm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
