version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DB_USER: zholamanoff
      DB_PASSWORD: kb971033
      DB_NAME: crm_db
      DB_HOST: postgres
      DB_PORT: 5432
      JWT_SECRET: b6989f4c50a0b46422a2d123e836c384  # Замените на свой уникальный секретный ключ

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: zholamanoff
      POSTGRES_PASSWORD: kb971033
      POSTGRES_DB: crm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
